# Definition for the mgr1 instance type
# Specifies which bootstrap script to run to set up this instance type and which roles
# to apply to this instance type

heat_template_version: 2014-10-16

parameters:
  Flavor:
    description: Flavor of the manager1 server
    type: string
    default: ec2.m3.2xlarge
  KeyName:
    description: Name of an existing ssh keypair
    type: string
  PrivateNet:
    description: Private network for pnda deployment
    type: string
  PrivateSubnet:
    description: Private network for pnda deployment
    type: string
  Image:
    type: string
  name:
    type: string
  SaltmasterIP:
    type: string
  cluster_name:
    type: string
  pnda_secgroup:
    type: string
  pnda_flavor:
    type: string
    default: standard
  logvolume_size:
    type: number
    default: 120
  signal_transport:
    type: string
  software_config_transport:
    type: string
  scheduler_group_hint:
    type: string
  PndaMirror:
    description: URL of a mirror for operating system package download
    type: string
    default: ''

resources:
  sec_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: CM SecurityGroup
      name:
        str_replace:
          template:
            cname-cdh-mgr1
          params:
            cname: { get_param: cluster_name }
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: PrivateNet }
      fixed_ips:
        - subnet_id: { get_param: PrivateSubnet }
      security_groups: [{ get_resource: sec_group }, { get_param: pnda_secgroup }]
  install_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: scripts/base_install.sh }
          params:
            $pnda_mirror$: { get_param: PndaMirror }
            $master_ip$: { get_param: SaltmasterIP }
            $pnda_cluster$: { get_param: cluster_name }
            $flavor$: { get_param: pnda_flavor }
            $log_volume_id$: { get_resource: logvolume }
            $roles$: 'cloudera_namenode,mysql_connector'
            $cloudera_role$: 'MGR01'
  install_deployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: [ logvolume_attachment ]
    properties:
      signal_transport: { get_param: signal_transport }
      config:
        get_resource: install_config
      server:
        get_resource: server

  logvolume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: logvolume_size }
      description: Volume for manager1 logs

  logvolume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: logvolume }
      instance_uuid: { get_resource: server }


  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: Image }
      flavor: { get_param: Flavor}
      key_name: { get_param: KeyName }
      networks:
        - port: { get_resource: port }
      software_config_transport: { get_param: software_config_transport }
      user_data_format: SOFTWARE_CONFIG
      config_drive: True
      scheduler_hints: 
        group: { get_param: scheduler_group_hint}

outputs:
  server_resource:
    description: Heat resource handle for the Nova compute server
    value:
      {get_resource: server}
