# Definition for the tools instance type
# Specifies which bootstrap script to run to set up this instance type and which roles
# to apply to this instance type

heat_template_version: 2014-10-16

parameters:
  Flavor:
    description: Flavor of the tools server
    type: string
    default: ec2.m3.large
  KeyName:
    description: Name of an existing ssh keypair
    type: string
  PrivateNet:
    description: Private network for pnda deployment
    type: string
  PrivateSubnet:
    description: Private network for pnda deployment
    type: string
  Image:
    type: string
  name:
    type: string
  SaltmasterIP:
    type: string
  NodeIndex:
    type: number
    default: 0
  sec_group:
    type: string
  cluster_name:
    type: string
  pnda_flavor:
    type: string
    default: standard
  pnda_secgroup:
    type: string
  signal_transport:
    type: string
  software_config_transport:
    type: string
  PndaMirror:
    description: URL of a mirror for operating system package download
    type: string
    default: ''

resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: PrivateNet }
      fixed_ips:
        - subnet_id: { get_param: PrivateSubnet }
      security_groups: [{ get_param: sec_group }, { get_param: pnda_secgroup }]
  install_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: scripts/base_install.sh }
          params:
            $pnda_mirror$: { get_param: PndaMirror }
            $flavor$: { get_param: pnda_flavor }
            $master_ip$: { get_param: SaltmasterIP }
            $pnda_cluster$: { get_param: cluster_name }
            $roles$: 'kafka_manager,platform_testing_general,elk'
  install_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: { get_param: signal_transport }
      config:
        get_resource: install_config
      server:
        get_resource: server

  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: Image }
      flavor: { get_param: Flavor }
      key_name: { get_param: KeyName }
      networks:
        - port: { get_resource: port }
      software_config_transport: { get_param: software_config_transport }
      user_data_format: SOFTWARE_CONFIG
      config_drive: True

outputs:
  server_resource:
    description: Heat resource handle for the Nova compute server
    value:
      {get_resource: server}
  hosts_entry:
    description: >
      Server's IP address and hostname in the /etc/hosts format
    value:
      str_replace:
        template: |
          PRIMARYIP PRIMARYHOST
        params:
          PRIMARYIP: {get_attr: [server, first_address]}
          PRIMARYHOST: {get_attr: [server, name]}
